title: Sandra T's data science portfolio
email: sssssan@gmail.com
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
domain: githubberst.github.io
url: https://githubberst.github.io
github_username:  githubberst

theme: jekyll-theme-minimal
# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 